### ISSUE TITLE
New composters do not drop when broken

### ISSUE THREAD

**Issue by Zokeyr** [pnk2u/More-Composter-Variants#1]
Issue: 
The new composters added are unable to be broken then picked up as an item. 

Steps to reproduce: 
Break any of the new composters (oak, spruce, etc.) using either bare hands or axe. Item doesn't drop.

**Comment by pnk2u** [comment]
Thanks for reporting this bug, I assume this was happening on 1.21?
It should be fixed in version 1.5.6. Feel free to close this issue if that fixes the bug or report back if it doesn't.

**Comment by Zokeyr** [comment]
Yup, works great now! Sorry for not stating the version number in the comment.
